---
## Time setting (KST)
- name: KST setup & time sync
  hosts: "{{ hosts }}"
  tasks:
    - name: KST setup (1/2)
      copy:
        src: /etc/localtime
        dest: /etc/localtime.bak
    - name: KST setup (1/2)
      copy:
        src: /usr/share/zoneinfo/Asia/Seoul
        dest: /etc/localtime
    - name: time sync (1/2)
      yum:
        name:
         - rdate
        state: present
    - name: time sync (2/2)
      command: rdate -s zero.bora.net && clock -w
      become: true

## chrony install
    - name: chrony install (1/3)
      yum:
        name:
         - chrony
        state: present
    - name: chrony install (2/3)
      command: cp /etc/chrony.conf /etc/chrony.conf.bak
    - name: chrony install (3/3)
      template:
        src: ./template/chrony.conf
        dest: /etc/chrony.conf

## chrony start
    - name: chrony start
      service: name=chronyd state=started

  vars:
    hosts: "all"
