---
## Time setting
- name: KST setting & sync timezone
  hosts: "{{ hosts }}"
  tasks:
    - name: KST setting (1/2)
      copy:
        src: /etc/localtime
        dest: /etc/localtime.bak
    - name: KST setting (2/2)
      copy:
        src: /usr/share/zoneinfo/Asia/Seoul
        dest: /etc/localtime
    - name: sync timezone (1/2)
      yum:
        name:
         - rdate
        state: present
    - name: sync timezone (2/2)
      command: rdate -s zero.bora.net && clock -w
      become: true
## chrony install
    - name: chrony install
      yum:
        name:
         - chrony
        state: present
    - name: chrony config
      command: cp /etc/chrony.conf /etc/chrony.conf.bak
    - name: Insert timezone
      template:
        src: ./template/chrony.conf
        dest: /etc/chrony.conf
## chrony start
    - name: chrony start
      service: name=chronyd state=started

## swap disable
    - name: Disable swap for current session
      command: swapoff -a
      become: true

    - name: Disable swap permanently, persist reboots
      replace:
        path: /etc/fstab
        regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
        replace: '#\1\2\3swap\4'
        backup: yes

## repo Package Install
    - name: repo Package Install
      apt:
       name:
        - apt-transport-https
        - software-properties-common
       state: present

## docker install
    - name: docker install (1/6)
      yum:
        update_cache: yes

    - name: docker install (2/6)
      yum: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']

    - name: docker install (3/6)
      yum_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: docker install (4/6)
      yum_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: docker install (5/6)
      yum:
        update_cache: yes

    - name: docker install (6/6)
      yum:
       name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
       state: present
    - shell: docker version
      register: shell_result

    - debug:
        var: shell_result.stdout_lines

  vars:
    hosts: "all"
