# kubeadm 업그레이드
yum upgrade kubeadm-1.21.2-0 --disableexcludes=kubernetes;
kubeadm upgrade node;
kubeadm upgrade apply v1.21.2

# kubelet, kubectl 업그레이드
yum upgrade kubelet-1.21.2-0 kubectl-1.21.2-0 --disableexcludes=kubernetes

# 서비스 재시작
sudo systemctl daemon-reload
sudo systemctl restart kubelet

---
## kubeadm 업그레이드
- name: kubeadm upgrade
  hosts: "{{ hosts }}"
  tasks:
    - name: kubeadm upgrade (1/3)
      yum:
       name:
        - kubeadm-{{ KUBE_Ver }}
       state: present

    - name: kubeadm upgrade (2/3)
    - command: kubeadm upgrade node
      register: shell_result
    - debug:
        var: shell_result.stdout_lines

    - name: kubeadm upgrade (3/3)
    - command: kubeadm upgrade apply v1.21.2
      register: shell_result
    - debug:
        var: shell_result.stdout_lines

# kubelet, kubectl 업그레이드
    - name: kubelet, kubectl upgrade (1/3)
      yum:
       name:
        - kkubelet-{{ KUBE_Ver }}
        - kubectl-{{ KUBE_Ver }}
       state: present

    - name: rpm check
    - command: rpm -qa | grep kube*
      register: shell_result
    - debug:
        var: shell_result.stdout_lines

## 서비스 재시작
    - name: service restart
      service: name=kubelet state=restarted enabled=yes

  vars:
    hosts: "all"
    KUBE_Ver: "1.21.2-0"
