---
apiVersion: v1
data:
  MARIADB_ROOT_PASSWORD: RWtmcmxkbmRiIzM=
kind: Secret
metadata:
  name: mariadb-pw
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: k1mariadb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mariadb
  selector:
    app: mariadb
---
apiVersion: v1
data:
  master.cnf: |
    [mysqld]
    log-bin
  slave.cnf: |
    [mysqld]
    super-read-only
kind: ConfigMap
metadata:
  labels:
    app: mariadb
  name: k1mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k1mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  serviceName: stateful-headless
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                values:
                - mariadb
                operator: In
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MARIADB_ROOT_PASSWORD
              name: mariadb-pw
        image: mariadb:10.2
        name: mariadb
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vol0
        - mountPath: /etc/mysql/mariadb.conf.d
          name: config
      volumes:
      - configMap:
          defaultMode: 420
          name: k1mariadb
        name: config
  volumeClaimTemplates:
  - metadata:
      name: vol0
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 5Gi
