## Time setting (KST)
- name: KST setup & time sync
  hosts: "{{ hosts }}"
  tasks:

## containerd presetup
    - name: containerd presetup (1/4)
      yum:
        update_cache: yes
    - name: containerd presetup (2/4)
      lineinfile:
          path: '/etc/modules-load.d/containerd.conf'
          line: "overlay \nbr_netfilter"
          insertbefore: EOF
          create: yes
    - name: containerd presetup (3/4)
      command: modprobe overlay
      command: modprobe br_netfilter
    - name: containerd presetup (4/4)
      lineinfile:
         path: '/etc/sysctl.d/99-kubernetes-cri.conf'
         line: "net.bridge.bridge-nf-call-iptables  = 1\n
                net.ipv4.ip_forward                 = 1\n
                net.bridge.bridge-nf-call-ip6tables = 1"
         insertbefore: EOF
         create: yes
    - command: sysctl --system
      register: shell_result2

    - debug:
        var: shell_result2.stdout_lines

## docker repo add
    - name: docker repo add (1/2)
      yum:
       name:
        - yum-utils
       state: present
    - name: docker repo add (2/2)
      command: |
               yum-config-manager \
               '--add-repo' \
               https://download.docker.com/linux/centos/docker-ce.repo

## containerd Install
    - name: containerd install (1/3)
      yum:
        update_cache: yes
    - name: containerd install (2/3)
      yum:
       name:
        - containerd
       state: present
    - shell: containerd -v
      register: shell_result

    - debug:
        var: shell_result.stdout_lines

    - name: containerd install (3/3)
      file:
          owner: "root"
          group: "root"
          path: /etc/containerd
          state: directory
          mode: 0755
    - shell: containerd config default | sudo tee /etc/containerd/config.toml

## containerd start
    - name: containerd start
      service: name=containerd state=started enabled=yes
  vars:
    hosts: "k-test"
